-- require("core.plugin_config.gruvbox")
-- require("core.plugin_config.catppuccin")
require("core.plugin_config.material")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.lsp_config")
require("core.plugin_config.completions")
require("core.plugin_config.autopairs")
require("core.plugin_config.gitsigns")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.comment")
require("core.plugin_config.prettier")
require("core.plugin_config.colorizer")
