idle_bg = "#313244"
idle_fg = "#cdd6f4"
info_bg = "#9399b2"
info_fg = "#cdd6f4"
good_bg = "#a6e3a1"
good_fg = "#1e1e2e"
warning_bg = "#f38ba8"
warning_fg = "#cdd6f4"
critical_bg = "#ff5555"
critical_fg = "#282a36"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
